### ISSUE TITLE
Fix golint reports

### ISSUE THREAD

**Issue by jaswdr** [jaswdr/faker#15]
Fix all reports from https://goreportcard.com/report/github.com/jaswdr/faker

**Comment by souvikmaji** [comment]
Please assign this to me, I can work on this.

**Comment by jaswdr** [comment]
Really appreciate the support @souvikmaji, assigned 👍

**Comment by souvikmaji** [comment]
Is this related to #9? as i see most lint errors are for missing comments  on exported fuctions.

**Comment by jaswdr** [comment]
@souvikmaji yes, I'll close the DocString issue in behalf of the new one

**Comment by souvikmaji** [comment]
Adding a comment on every exported function is a very mundane and repetitive task. 
Sorry, but I have lost interest in this.

**Comment by jaswdr** [comment]
@souvikmaji no problem, feel free to check others issues, maybe there is something you interested on

**Comment by ronaudinho** [comment]
given the issue is fixing [goreportcard](https://goreportcard.com/report/github.com/jaswdr/faker), would adding template docs work for you? @jaswdr

**Comment by jaswdr** [comment]
I guess yes @ronaudinho, make a try and send a PR, I'll take a look and we can discuss the solution

**Comment by ronaudinho** [comment]
#23 i've drafted a PR, let me know if you are fine with it

**Comment by jaswdr** [comment]
@ronaudinho thanks for the help, I've review and apply remaining changes to all violations of GoReport, now we are 100% green!

I'm closing this issue since we reach our goal
