### ISSUE TITLE
Fix transient issues in tests

### ISSUE THREAD

**Issue by jaswdr** [jaswdr/faker#19]
Some tests randomly fail in some conditions, see below some failed cases:

1. https://travis-ci.org/github/jaswdr/faker/jobs/733173740
1. https://travis-ci.org/github/jaswdr/faker/jobs/732641824
1. https://travis-ci.org/github/jaswdr/faker/jobs/730437529
1. https://travis-ci.org/github/jaswdr/faker/jobs/730137940
1. https://travis-ci.org/github/jaswdr/faker/jobs/730137939
1. https://travis-ci.org/github/jaswdr/faker/jobs/729186249

We need to fix this to have reliable tests and avoid false positives fails.

**Comment by HemantJoshi11** [comment]
I will try to fix it

**Comment by HemantJoshi11** [comment]
Looks like it's already fixed.

**Comment by jaswdr** [comment]
@HemantJoshi11 sorry, true, I forget to close this issue, I'm closing it for know, if I see any other transient issue in tests we can reopen this or open a new issue with the related errors.
