### ISSUE TITLE
Make project compatible with new versions of Go

### ISSUE THREAD

**Issue by jaswdr** [jaswdr/faker#20]
Our tests are failing for new versions of Go for all operational systems, see https://travis-ci.org/github/jaswdr/faker/builds/733533193

We need to fix this to make the library compatible and reliable with all new Go versions.

**Comment by HemantJoshi11** [comment]
let me try

**Comment by jaswdr** [comment]
sure @HemantJoshi11, the basic idea is test and fix all errors that appear in Travis, if you need any help with that please let me know.

**Comment by HemantJoshi11** [comment]
@jaswdr Pls review

**Comment by jaswdr** [comment]
merged, 💯 congratulations on your first PR and fixed Issue

**Comment by ocean** [comment]
Can I pick up this one?
