### ISSUE TITLE
[BUG] IntBetween not giving correct output

### ISSUE THREAD

**Issue by ab22** [jaswdr/faker#31]
**Describe the bug**
While trying to fix the test coverage for ticket #28, I found out that the `IntBetween` function does not return values correctly for some cases. 

Example: https://github.com/jaswdr/faker/blob/master/person.go#L136-L142

**To Reproduce**

Go playground [sample snippet](https://play.golang.org/p/atgNz0GjuY5). 

```go
f := faker.New()

for i := 0; i < 10; i++ {
	fmt.Println(f.IntBetween(0, 1))
}
```

The output will always be 0. The current [IntBetween](https://github.com/jaswdr/faker/blob/master/faker.go#L85-L93) function does not handle the range `[0, 1]` correctly.

**Expected behavior**
I would expect that `IntBetween(0, 1)` would return 0s and 1s randomly. 

Also, I would like to get clarification if the function should return numbers between 0-1 in this case. I do have a fix for this already but I am seeing some other tests fail because of the way `IntBetween` is being used. For example on [address.go](https://github.com/jaswdr/faker/blob/master/faker.go#L116-L119):

```go
func (f Faker) RandomStringElement(s []string) string {
	i := f.IntBetween(0, len(s))
	return s[i]
}
```

A number between `0` and `len(s)` would cause random `index out of range` errors because it would sometimes return `len(s)`.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: any
 - `go version` output: go version go1.15.2 linux/amd64

**Additional context**

**Comment by jaswdr** [comment]
I've tested with latest version and it is generating random values between the range:

```go
f := New()
for i := 0; i < 100; i++ {
    fmt.Printf("%d,", f.IntBetween(0, 1))
}
```

Output:

```
1,1,1,1,1,0,1,0,0,0,0,1,0,1,0,0,1,1,1,0,1,0,0,0,1,1,1,0,0,1,1,0,1,1,1,0,1,1,1,0,1,0,0,1,1,1,0,0,1,1,1,1,1,1,0,1,0,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,1,0,1,0,1,1,0,
````
