### ISSUE TITLE
[FEATURE] New generators, Wave 1

### ISSUE THREAD

**Issue by jaswdr** [jaswdr/faker#40]
File

- [ ] JSON(jo *JSONOptions) []byte
- [ ] XML(xo *XMLOptions) []byte
- [x] Extension() string
- [x] MimeType() string

Person

- [x] Person() *PersonInfo
- [x] Name() string
- [x] NamePrefix() string
- [x] NameSuffix() string
- [x] FirstName() string
- [x] LastName() string
- [x] Gender() string
- [x] SSN() string
- [x] Contact() *ContactInfo
- [x] Email() string
- [x] Phone() string
- [x] PhoneFormatted() string
- [ ] ~~Teams(people []string, teams []string) map[string][]string~~

Generate

- [x] Struct(v interface{})
- [x] Map() map[string]interface{}
- [ ] Generate(value string) string

Auth

- [x] Username() string
- [x] Password(lower bool, upper bool, numeric bool, special bool, space bool, num int) string

Address

- [x] Address() *AddressInfo
- [x] City() string
- [x] Country() string
- [x] CountryAbr() string
- [x] State() string
- [x] StateAbr() string
- [x] Street() string
- [x] StreetName() string
- [x] StreetNumber() string
- [x] StreetPrefix() string
- [x] StreetSuffix() string
- [x] Zip() string
- [x] Latitude() float64
- [x] LatitudeInRange(min, max float64) (float64, error)
- [x] Longitude() float64
- [x] LongitudeInRange(min, max float64) (float64, error)

Game

- [x] Gamertag() string

Beer

- [x] BeerAlcohol() string
- [x] BeerBlg() string
- [x] BeerHop() string
- [x] BeerIbu() string
- [x] BeerMalt() string
- [x] BeerName() string
- [x] BeerStyle() string
- [x] BeerYeast() string

Cars

- [x] Vehicle() *VehicleInfo
- [x] CarMaker() string
- [x] CarModel() string
- [x] VehicleType() string
- [x] FuelType() string
- [x] TransmissionGearType() string

Words

- [x] Noun() string
- [x] Verb() string
- [x] Adverb() string
- [x] Preposition() string
- [x] Adjective() string
- [x] Word() string
- [x] Sentence(wordCount int) string
- [x] Paragraph(paragraphCount int, sentenceCount int, wordCount int, separator string) string
- [x] LoremIpsumWord() string
- [x] LoremIpsumSentence(wordCount int) string
- [x] LoremIpsumParagraph(paragraphCount int, sentenceCount int, wordCount int, separator string) string
- [x] Question() string
- [x] Quote() string
- [x] Phrase() string

Foods

- [x] Fruit() string
- [x] Vegetable() string
- [x] Breakfast() string
- [x] Lunch() string
- [x] Dinner() string
- [x] Snack() string
- [x] Dessert() string

Misc

- [x] Bool() bool
- [x ] UUID() string

Colors

- [x] Color() string
- [x] HexColor() string
- [x] RGBColor() []int
- [x] SafeColor() string

Internet

- [x] URL() string
- [x] ImageURL(width int, height int) string
- [x] DomainName() string
- [x] DomainSuffix() string
- [x] IPv4Address() string
- [x] IPv6Address() string
- [x] StatusCode() string
- [x] SimpleStatusCode() int
- [x] LogLevel(logType string) string
- [x] HTTPMethod() string
- [x] UserAgent() string
- [x] ChromeUserAgent() string
- [x] FirefoxUserAgent() string
- [x] OperaUserAgent() string
- [x] SafariUserAgent() string

Date/Time

- [x] Date() time.Time
- [x] DateRange(start, end time.Time) time.Time
- [x] NanoSecond() int
- [x] Second() int
- [x] Minute() int
- [x] Hour() int
- [x] Month() string
- [x] Day() int
- [x] WeekDay() string
- [x] Year() int
- [x] TimeZone() string
- [x] TimeZoneAbv() string
- [x] TimeZoneFull() string
- [x] TimeZoneOffset() float32
- [x] TimeZoneRegion() string

Payment

- [x] Price(min, max float64) float64
- [x] CreditCard() *CreditCardInfo
- [x] CreditCardCvv() string
- [x] CreditCardExp() string
- [x] CreditCardNumber(*CreditCardOptions) string
- [x] CreditCardType() string
- [x] Currency() *CurrencyInfo
- [x] CurrencyLong() string
- [x] CurrencyShort() string
- [x] AchRouting() string
- [x] AchAccount() string
- [x] BitcoinAddress() string
- [x] BitcoinPrivateKey() string

Company

- [x] BS() string
- [x] BuzzWord() string
- [x] Company() string
- [x] CompanySuffix() string
- [x] Job() *JobInfo
- [x] JobDescriptor() string
- [x] JobLevel() string
- [x] JobTitle() string

Hacker

- [x] HackerAbbreviation() string
- [x] HackerAdjective() string
- [x] HackerIngverb() string
- [x] HackerNoun() string
- [x] HackerPhrase() string
- [x] HackerVerb() string

Hipster

- [x] HipsterWord() string
- [x] HipsterSentence(wordCount int) string
- [x] HipsterParagraph(paragraphCount int, sentenceCount int, wordCount int, separator string) string

App

- [x] AppName() string
- [x] AppVersion() string
- [x] AppAuthor() string

Animal

- [x] PetName() string
- [x] Animal() string
- [x] AnimalType() string
- [x] FarmAnimal() string
- [x] Cat() string
- [x] Dog() string

Emoji

- [x] Emoji() string // 🤣
- [x] EmojiDescription() string // winking face
- [x] EmojiCategory() string // Smileys & Emotion
- [x] EmojiAlias() string // smiley
- [x] EmojiTag() string // happy

Languages

- [x] Language() string
- [x] LanguageAbbreviation() string
- [x] ProgrammingLanguage() string
- [x] ~~ProgrammingLanguageBest() string~~

Numbers

- [x] Number(min int, max int) int
- [x] Int8() int8
- [x] Int16() int16
- [x] Int32() int32
- [x] Int64() int64
- [x] Uint8() uint8
- [x] Uint16() uint16
- [x] Uint32() uint32
- [x] Uint64() uint64
- [x] Float32() float32
- [x] Float32Range(min, max float32) float32
- [x] Float64() float64
- [x] Float64Range(min, max float64) float64
- [x] ShuffleInts(a []int)
- [x] RandomInt(i []int) int

String

- [x] Digit() string
- [x] DigitN(n int) string
- [x] Letter() string
- [x] LetterN(n int) string
- [x] Lexify(str string) string
- [x] Numerify(str string) string
- [x] ShuffleStrings(a []string)
- [x] RandomString(a []string) string

**Comment by haydenlinder** [comment]
Is `Verb()` available?
