### ISSUE TITLE
[QUESTION] Random numbers in struct

### ISSUE THREAD

**Issue by Hedgehogues** [jaswdr/faker#47]
Hello. Can I fill my struct with random numbers. But not only max numbers.

**Comment by jaswdr** [comment]
@Hedgehogues unfortunately the current implementation doesn't allow to define a range, the lines that define with Int value would be generated start [here](https://github.com/jaswdr/faker/blob/master/struct.go#L121), but it is possible and I see as a valid use case, I would send a PR for this.

**Comment by jaswdr** [comment]
I've fixed the issue of generating only max values in #54
