### ISSUE TITLE
[BUG] E164Number generates invalid E164 phone number

### ISSUE THREAD

**Issue by augbed** [jaswdr/faker#59]
**Describe the bug**
E164Number sometimes generates invalid E164 phone number. 

**Expected behavior**
E164Number should return a phone number that doesn't start with 0.

**Additional context**
E164Number works by generating random 11 digit number with + as a prefix but 0 as a first digit is an invalid country code. Fairly popular way of checking validity of E164 numbers is to do a regex match like: 
```
^\+[1-9]\d{1,14}$ 
``` 
For which this function fails 1 out of 10 times.

**Comment by jaswdr** [comment]
PR merged and released in v1.4.2, thank you for the issue report and PR for the fix
