### ISSUE TITLE
[BUG] build fails on 32 bit system

### ISSUE THREAD

**Issue by maxsupermanhd** [jaswdr/faker#65]
**Describe the bug**
I am failing to build this package on raspberry pi 3b because of integer overflow here https://github.com/jaswdr/faker/blob/v1.4.2/payment.go#L26

![image](https://user-images.githubusercontent.com/20772987/136218910-ac0d678f-86ab-4687-b3d6-2c57bdd456ee.png)

**Comment by jaswdr** [comment]
New version v1.4.3 is released with the fix, @maxsupermanhd please update your local version and try again
