### ISSUE TITLE
[FEATURE] Bitcoin Address Support

### ISSUE THREAD

**Issue by fzn0x** [jaswdr/faker#78]
**Is your feature request related to a problem? Please describe.**
Bitcoin Address Support with available standard implementation

**Comment by xlanor** [comment]
@jaswdr, I would like to work on this too, but would like to have some clarification:

- Currently, there are four types of Bitcoin addresses avaliable (from what I can tell). However, I am unable to find a fixed spec sheet anywhere pertaining to the length. Should we fix a length at maybe say, 60, and subsequently tweak it as need be? it may be incorrect at the start, but I do not have the specific knowledge on Bitcoin addresses. Unless @bl0cknumber can provide more concrete details?
- I was thinking of structuring this under a `Crypto` generator so that we could have further extensions in the future, such as `f.Crypto().Bitcoin().Address()` and `f.Crypto().Ethereum().Address()`, what do you think?

**Comment by xlanor** [comment]
Yep! That's actually the line of thought I was going down. However, these are Bitcoin specific addresses in nature. Ethereum addresses, for example, would be different

Even for each type, the length of the address, for example, which is a fairly important factor to note when generating the address, does not seem to have an official source/paper describing the maximum or minimum length.


For example, [this wiki](https://en.bitcoin.it/wiki/Invoice_address#:~:text=Most%20Bitcoin%20invoice%20addresses%20are,used%20to%20prevent%20visual%20ambiguity) fixes it at 30ish, whereas [BitcoinTalk](https://bitcointalk.org/index.php?topic=5261325.msg54779447#msg54779447) says that for Bech32, it can go up to 62 characters.

**Comment by bl0cknumber** [comment]
> @jaswdr, I would like to work on this too, but would like to have some clarification:
> 
> * Currently, there are four types of Bitcoin addresses avaliable (from what I can tell). However, I am unable to find a fixed spec sheet anywhere pertaining to the length. Should we fix a length at maybe say, 60, and subsequently tweak it as need be? it may be incorrect at the start, but I do not have the specific knowledge on Bitcoin addresses, apart from their prefixes and non-allowed characters or digits, but the discussion on maximum and minimum allowed lengths seems to have conflicting information and no official source. Unless @bl0cknumber can provide more concrete details?
> * I was thinking of structuring this under a `Crypto` generator so that we could have further extensions in the future, such as `f.Crypto().Bitcoin().Address()` and `f.Crypto().Ethereum().Address()`, what do you think?

**Bitcoin** address would take up 26-35, [see here for the information from Bitcoin wiki](https://en.bitcoin.it/wiki/Invoice_address)

> A Bitcoin invoice address, or simply invoice, is an identifier of 26-35 alphanumeric characters, beginning with the number 1, 3 or bc1 that represents a possible destination for a bitcoin payment. Invoices can be generated at no cost by any user of Bitcoin. It is also possible to get a Bitcoin invoice address using an account at an exchange or online wallet service.

There are currently three invoice address formats in use:

P2PKH which begin with the number 1, eg: 1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2.
P2SH type starting with the number 3, eg: 3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy.
Bech32 type starting with bc1, eg: bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq.

**Ethereum** address would take up 42 characters long for the prefixed address, [see here for the information from Ethereum documentation glossary](https://ethdocs.org/en/latest/glossary.html)

> An Ethereum address represents an account. For EOA, the address is derived as the last 20 bytes of the public key controlling the account, e.g., cd2a3d9f938e13cd947ec05abc7fe734df8dd826. This is a hexadecimal format (base 16 notation), which is often indicated explicitly by appending 0x to the address. Web3.js and console functions accept addresses with or without this prefix but for transparency we encourage their use. Since each byte of the address is represented by 2 hex characters, a prefixed address is 42 characters long. Several apps and APIs are also meant to implement the new checksum-enabled address scheme introduced in the Mist Ethereum wallet as of version 0.5.0.

**Comment by bl0cknumber** [comment]
There are 62 characters in a Taproot address, 42 in a Segwit address, and 34 characters in the two Legacy addresses available in Trezor Suite.

**Comment by xlanor** [comment]
Cool. In that case, what I will probably do is to do a variable length function signature where the user would have to specify the signature length. This allows for the use case whereby in future, if new address standards are implemented (like increasing length) it will not result in a backward breaking change for existing users of the library.

Can I confirm for the prefix - is the count inclusive of the prefix? @bl0cknumber 

ccing @jaswdr to comment on the above proposal

**Comment by jaswdr** [comment]
@xlanor LGTM, the only thing that maybe is interesting to change is to not require that the user specifies the length, but instead generate a random length (with [IntBetween](https://github.com/jaswdr/faker/blob/4c5f5d084f9746d1f476130fc1ecded5f464bc06/faker.go#L142)) and use that to generate the value, and if the user want to have a specific length you can create some **WithLength** variants.

**Comment by xlanor** [comment]
Sounds good. I'll get started on it and should have a PR ready in the next few days

**Comment by jaswdr** [comment]
Both PRs were merged, I'm closing this for now

**Comment by fzn0x** [comment]
> Both PRs were merged, I'm closing this for now

Thanks!
