### ISSUE TITLE
[FEATURE] Generate a string of a certain length

### ISSUE THREAD

**Issue by xlanor** [jaswdr/faker#81]
**Is your feature request related to a problem? Please describe.**
Currently looking for a simple mechanism to fake strings of a certain length across multiple projects.

**Describe the solution you'd like**
Add a calling function in a for loop using `f.RandomLetter` and generating it `l` times to generate a string of length `l`

**Comment by jaswdr** [comment]
Released in [v1.10.0](https://github.com/jaswdr/faker/releases/tag/v1.10.0), thank you very much for your contribution 😄
