### ISSUE TITLE
[BUG] Some fake emails fails email validation regex

### ISSUE THREAD

**Issue by jcobhams** [jaswdr/faker#83]
**Describe the bug**
When using `faker.Internet().Email()`, some generated fake emails fails email regex patterns.
Some names like `"O\"Connell", "O\"Conner", "O\"Hara", "O\"Keefe", "O\"Kon"` found in [here](https://github.com/jaswdr/faker/blob/4c5f5d084f9746d1f476130fc1ecded5f464bc06/person.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L92) trips up a regex pattern for validating email addresses.

Regex: `/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g`

**To Reproduce**
```go
In the off chance that you can get the library to pick one of these names and generate a fake email, you can run it against this regex validator: https://regexr.com/3e48o
```

**Expected behavior**
That `faker.Internet().Email()` returns a semantically valid email address format.

**Screenshots**
![Screen Shot 2022-01-26 at 7 58 19 PM](https://user-images.githubusercontent.com/5455248/151272154-f6368de6-584e-499b-b6ac-74c1d4cde79a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - `go version` output: go version go1.17.6 darwin/amd64

**Comment by jaswdr** [comment]
@jcobhams thank you for reporting 👍 , I've merged the fix for this issue and released it in 1.10.1, the fix will only generate names with valid characters, replacing with "_" otherwise, and includes a validation in tests to check that the email is valid to improve detection of this in the future.

**Comment by jcobhams** [comment]
Thanks for the quick fix and prompt response @jaswdr 
🙏

**Comment by babaralishah** [comment]
Hi 
I am on Angular

And using the below regex:

`'^[a-z0-9]+([._-]?[a-z0-9]+)+@[a-z0-9]+([._-]?[a-z0-9]+)+\\.[a-z]{2,3}$'`

But its not fulfilling my requirement, my requirement is below:

`saa5@me-d_d_u.co`

please anyone tell me, why this regex is not working for my above mentioned case.

Regards
Babar Ali Shah
